services:
  api1:
    build: .
    container_name: api1
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - redis

  api2:
    build: .
    container_name: api2
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
